Add schema-migrator Helm chart version 0.1.2

diff --git a/helm/ssl-proxy/charts/schema-migrator/templates/bootstrap-job.yaml b/helm/ssl-proxy/charts/schema-migrator/templates/bootstrap-job.yaml
--- a/helm/ssl-proxy/charts/schema-migrator/templates/bootstrap-job.yaml
+++ b/helm/ssl-proxy/charts/schema-migrator/templates/bootstrap-job.yaml
@@ -64,6 +64,23 @@ spec:
                   --username "$APP_USERNAME" --new-password "$APP_PASSWORD" --temporary >/dev/null
               fi
 
+              client_uuid="$($KCADM get clients --config "$CONFIG" -r "$REALM" \
+                -q "clientId=$CLIENT_ID" --fields id --format csv --noquotes \
+                | grep -v '^id$' | head -n 1)"
+              if [ -z "$client_uuid" ]; then
+                echo "Keycloak client $CLIENT_ID was not found" >&2
+                exit 1
+              fi
+              if [ "$PUBLIC_ORIGIN" = "$UI_ORIGIN" ]; then
+                redirect_uris="[\"$PUBLIC_ORIGIN/*\"]"
+                web_origins="[\"$PUBLIC_ORIGIN\"]"
+              else
+                redirect_uris="[\"$PUBLIC_ORIGIN/*\",\"$UI_ORIGIN/*\"]"
+                web_origins="[\"$PUBLIC_ORIGIN\",\"$UI_ORIGIN\"]"
+              fi
+              "$KCADM" update "clients/$client_uuid" --config "$CONFIG" -r "$REALM" \
+                -s "redirectUris=$redirect_uris" -s "webOrigins=$web_origins" >/dev/null
+
               "$KCADM" add-roles --config "$CONFIG" -r "$REALM" \
                 --uusername "$APP_USERNAME" --cclientid "$CLIENT_ID" --rolename "$ADMIN_ROLE"
           env:
@@ -80,6 +97,10 @@ spec:
               value: {{ .Values.keycloak.realm | quote }}
             - name: CLIENT_ID
               value: {{ .Values.keycloak.clientId | quote }}
+            - name: PUBLIC_ORIGIN
+              value: {{ include "ssl-proxy.schemaMigrator.publicOrigin" . | quote }}
+            - name: UI_ORIGIN
+              value: {{ include "ssl-proxy.schemaMigrator.uiOrigin" . | quote }}
             - name: ADMIN_ROLE
               value: {{ .Values.keycloak.adminRole | quote }}
             - name: APP_USERNAME
